from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet
from datetime import datetime
import os


def generate_report(filename, result, confidence):

    os.makedirs("reports", exist_ok=True)

    report_name = f"{os.path.splitext(filename)[0]}_report.pdf"
    report_path = os.path.join("reports", report_name)

    doc = SimpleDocTemplate(report_path)
    styles = getSampleStyleSheet()
    story = []

    now = datetime.now()

    story.append(Paragraph("<b>Deepfake Investigation Report</b>", styles["Title"]))
    story.append(Paragraph("<br/><br/>", styles["Normal"]))

    story.append(Paragraph(f"<b>Date:</b> {now.strftime('%d-%m-%Y')}", styles["Normal"]))
    story.append(Paragraph(f"<b>Time:</b> {now.strftime('%I:%M:%S %p')}", styles["Normal"]))
    story.append(Paragraph(f"<b>File Name:</b> {filename}", styles["Normal"]))
    story.append(Paragraph(f"<b>Prediction:</b> {result}", styles["Normal"]))
    story.append(Paragraph(f"<b>Confidence:</b> {confidence:.2f}%", styles["Normal"]))

    story.append(Paragraph("<br/><br/>", styles["Normal"]))
    story.append(
        Paragraph(
            "Generated by <b>Deepfake Investigation System</b>",
            styles["Normal"],
        )
    )

    doc.build(story)

    return report_name